function model = PLSDA_main(X,Y,nComp,varNames,LASSO,ortho,multilevel,cvStyle,nPerm,categories,palette)
%% PLSDA framework, Dolatshahi Lab
%% Author: Remziye Erdogan, 06/2021
%% Updated: 04/2026
% This script performs PLSDA using the MATLAB built-in function,
% 'plsregress'. Two class models are very common in PLSDA. The original
% version of this package (2021) was hard-coded to fit two class models.
% This version has been updated to generalize to multi-class problems.

arguments
    X % The input matrix for PLSDA. Need not be z-scored as this will happen within the this function.
    Y % The response matrix for future PLSDA.
    nComp % The number of components for your model (an integer). Must be nComp >= width(Y).
    varNames % A horizontal (1xn) cell array of variable names. 
    LASSO % A cell array specifying if you wish to perform LASSO feature selection, and if so, the input parameters.
    % e.g. {LASSO,alpha,stability} = {'yes',1,0.8}
    ortho % A string specifying if you wish to orthogonalize your model. If 'orthogonal', will run the orthogonalization routine.
    multilevel % A string specifying if you wish to perform multilevel preprocessing. If 'multilevel', will mean center data pairs before z-scoring.
    % See note below on multilevel preprocessing. It is important to only
    % flag this for paired samples, and the samples must follow a specific
    % order for it to work properly. 
    cvStyle % A cell array specifying cross-validation style and parameters.
    % e.g. {'kfold',5} or {'loo',''}
    nPerm % An integer, number of permutations (random shuffling of the class labels in Y).
    categories % A cell array (1xm) specifying the names of your classes.
    % e.g. {'drug','control'}
    palette % An nx3 matrix defining your color palette for plotting.
end

% USER OPTIONS %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Orthogonalization:  forces maximum variance in the direction of LV1.
% Makes for easier model interpretation.

% Feature selection using LASSO/Elastic net:  optional feature selection
% step included using run_elastic_net function (original script by 
% Shay Ladd - a version is included in this package).

% Multilevel preprocessing:  use ONLY if you have matched samples and you
% want to account for this paired data structure in your analysis. Data
% MUST be provided with all the rows for the first class concatenated on
% top of all the rows for the second class, and samples MUST be in the same
% order within both classes.

% Cross-validation:
% The user can choose from the following CV options using the 'cv_style' input:
        %K-fold CV with 'k' folds: {'kfold',k}; 
        %Leave-one-out CV: {'loo'};
% The model will report prediction accuracy estimates over 100 rounds of
% cross validation. This can be compared to a distribution generated by
% random permutations of the y-labels.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% A NOTE ON CROSS VALIDATION %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% If you perform LASSO/elastic net feature selection, it is STRONGLY
% recommended you do not rely on the built-in cross validation framework to
% estimate your model's prediction accuracy. This is because this script
% uses all observations to perform feature selection, followed by
% cross-validation using that same set of features that have ALREADY SEEN
% the holdout data. This approach may lead to overfitting the model. It is
% better practice to validate models with a feature selection step by
% performing independent rounds of feature selection for each data
% partition, then predicting the hold out data using the feature set
% determined using ONLY the training data.

% This approach can be COMPUTATIONALLY EXPENSIVE. It is recommended to
% train your model and identify your features first, then run
% cross-validation independently after you have established your optimal
% model.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% OUTPUTS %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% model = a structure with the following fields:
    %XLoadings,YLoadings = predictor and response loadings
    %XScores,YScores = predictor and response scores
    %BETA = matrix of coefficient estimates for PLSR
    %PCTVAR = percentage of variance explained by the regression model (first
    %row is variance in X, 2nd row is variance in Y)
    %MSE = estimated mean squared error after performing cross-validation
    %stats = contains PLS weights, T^2 statistic, and residuals
    %CV_accuracy = model prediction accuracy over 100 rounds of cross
    %validation.
    %R2 = model goodness-of-fit criteria.
    %p_perm = the p-value output by the permutation test; see 'permtest.m'
    %for more details on how this is calculated and interpretation
    %varNames = names of the variables in X
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% There are more outputs than this! Need to update further. %%%%%%%%%%%%%%%

close all;

%% Save a version of X data before any optional preprocessing steps %%%%%%%
% Save the data prior to z-scoring and feature selection (helpful for univariate plots).
X_pre_z_total = X; 
X_pre_z = X;
% Save the full list of variable names prior to (optional) feature
% selection.
varNames_old = varNames;

%% LASSO/Elastic net feature selection (OPTIONAL) %%%%%%%%%%%%%%%%%%%%%%%%%
clear lasso_feat b fitInfo minMSE minMSE_Lambda
if strcmp(string(LASSO{1}),'yes')

[varNames,ia] = run_elastic_net(zscore(X), Y, varNames_old, 'minMSE',LASSO{2}, 100, LASSO{3}, cvStyle{2});

    X = X(:,ia); %subset X to only contain LASSO-selected features
    X_pre_z = X_pre_z_total(:,ia); %subset X_pre_z to only LASSO-selected features

    model.X_pre_z_total = X_pre_z_total;
    model.varNames_old = varNames_old;
    model.lasso_idx = ia;
    model.X_pre_z = X_pre_z;

    % build LASSO correlation network
    n=1;
    [rho,pval]=corr(model.X_pre_z,model.X_pre_z_total,'type','Pearson');
    for i = 1:width(model.X_pre_z)
        for j = 1:width(model.X_pre_z_total)
    
        source_table(n) = model.varNames_old(model.lasso_idx(i));
        target_table(n) = model.varNames_old(j);
        rho_table(n) = rho(i,j);
        pval_table(n) = pval(i,j);
        n=n+1;
        end
    end
    pval_corrected = pval_table*length(pval_table); % p-vlaues are Bonferroni corrected
    model.LASSO_network = table(source_table',target_table',rho_table',...
        pval_table',pval_corrected','VariableNames',...
        {'LASSO_Feature','Correlate','rho','pval','pval_Bonferroni'});

    % Remove self-correlations
    model.LASSO_network = model.LASSO_network(~strcmp(model.LASSO_network.LASSO_Feature,model.LASSO_network.Correlate),:);

end

%% Multilevel pre-processing for paired samples (OPTIONAL) %%%%%%%%%%%%%%%%
if strcmp(multilevel,'multilevel')
    % multilevel denoising
    for i = 1:height(X)/2
        pairwise_mean = mean([X(i,:);X(i+height(X)/2,:)]);
        X(i,:) = X(i,:) - pairwise_mean;
        X(i+height(X)/2,:) = X(i+height(X)/2,:) - pairwise_mean;
    end

% else
%         X = zscore(X);
end

X = zscore(X);

%% Orthogonalization (OPTIONAL) %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if strcmp(ortho,'orthogonal')
    tol = 0.1; % YOU CAN ADJUST THIS TOLERANCE VALUE IF THE MODEL DOES NOT PERFECTLY ORTHOGONALIZE
    [X_filt] = OPLS(X,Y,tol);
    X = X_filt;
end

%% Run PLSDA with 100 rounds of cross validation %%%%%%%%%%%%%%%%%%%%%%%%%%
clear TSS PLSR_XLoading PLSR_YLoading PLSR_XScore PLSR_YScore PLSR_yfit;
clear R2 Q2;
for n = 1:100 % 100 rounds of cross validaton

% Select cross-validation style
if strcmp(cvStyle{1},'kfold')
    k_fold = cvStyle{2};
    cvp = cvpartition(height(X),'KFold',k_fold);
elseif strcmp(cvStyle{1},'loo')
    cvp = cvpartition(height(X),'Leaveout');  
end   

Y_predicted = zeros(size(Y));

if strcmp(cvStyle{1},'kfold')
    
    for i = 1:cvStyle{2} % loop through each fold of data

        % partition data into training and testing sets
        [training_set] = training(cvp,i);
        [testing_set] = test(cvp,i);

        % train a model on the training set
        [~,~,~,~,BETA,~,~,~] = plsregress(X(training_set,:),Y(training_set,:),nComp,'cv','resubstitution');

        % predict class labels of the testing set
        Y_predicted(testing_set,:) = [ones(size(X(testing_set,:),1),1) X(testing_set,:)]*BETA;

    end

elseif strcmp(cvStyle{1},'loo')

    for i = 1:height(Y) % loop through each sample one at a time

        % partition the data
        testing_set = i;
        training_set = setdiff(1:height(X),i);

        % train a model on the training set
        [~,~,~,~,BETA,~,~,~] = plsregress(X(training_set,:),Y(training_set,:),nComp,'cv','resubstitution');

        % predict class labels of the testing set
        Y_predicted(testing_set,:) = [ones(size(X(testing_set,:),1),1) X(testing_set,:)]*BETA;

    end

end   

% Determine cross validation accuracy.
% This package does not currently let you adapt the threshold for calling
% your class labels (this would be a worthy improvement!).
% Instead, it assumes whichever class is predicted highest (closest to 1)
% is the positive class prediction, and is labeled as such.

[~,idx]=max(Y_predicted,[],2);
Y_predicted_new = zeros(size(Y_predicted));

% Whichever column is predicted the highest, assign it the positive class
% prediction.
for i = 1:height(Y_predicted)
    Y_predicted_new(i,idx(i))=1;
end

% For two class problems, go thru each row in Y and check if the
% predictions match the actual class labels.
if width(Y)==2
    correct = 0;
    for i = 1:length(Y)
        if Y(i,:) == Y_predicted_new(i,:) 
            correct = correct + 1; %If prediction and actual label match, increase count of "correct" assignments.
        end
    end
    
% Determine the correct classification rate - save one CV_accuracy score for each round of cross-validation.
CV_accuracy(n) = correct/length(Y)*100;
    
% For multiclass problems, calculate the accuracy for each class prediction
% separately as well as an overall accuracy score.
elseif width(Y)>2 
    Yw = width(Y);
    correct = zeros(1,Yw);
    for i = 1:length(Y)
        for w = 1:Yw
            if Y(i,w) == Y_predicted_new(i,w) 
                correct(w) = correct(w) + 1; 
            end
        end
    end 

CV_accuracy(n,:) = correct/length(Y)*100;

end

end

% Plot an ROC curve and caluclate ROC-AUC based on cross-validation
% performance.
[x_roc,y_roc] = perfcurve(Y(:,1),Y_predicted(:,1),1); % 'Nboot' to do confidence interval
figure(1); plot(x_roc,y_roc,'lineWidth',2); hold on
plot([0,1],[0,1],'k--')
xlabel('False Positive Rate'); ylabel('True Positive Rate')
auc = trapz(x_roc,y_roc);
title(append('AUC=',string(auc)))

%% Train a PLSDA model using all the data %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Calculate total sum of squares (TSS)
TSS = sum((Y-mean(Y)).^2);

[XLoading,YLoading,XScore,YScore,BETA,PCTVAR,MSE,stats] = plsregress(X,Y,nComp,'cv',cvp);

% Q2 = [0 1-length(Y)*MSE(2,2:end)/TSS]; [Q2max,Q2idx] = max(Q2);

% Determine R2 (model performance) score
R2 = [0 cumsum(PCTVAR(2,:))];

%% Permutation test with random shuffling of the class labels %%%%%%%%%%%%%
[p_perm,CV_accuracy_perm] = permtest(X,Y,nComp,nPerm,cvp,'wilcoxon','PLSDA',CV_accuracy);

%% Save output data structure %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
model.Xdata = X;
model.Ydata = Y;
model.XLoading = XLoading;
model.YLoading = YLoading;
model.XScore = XScore;
model.YScore = YScore;
model.beta = BETA;
model.PCTVAR = PCTVAR;
model.ncomp = nComp;
model.CV_accuracy = CV_accuracy;
model.R2 = R2;
model.p_perm = p_perm;
model.varNames = varNames;
model.stats = stats;
model.MSE = MSE(2,nComp+1);
model.XpreZ = X_pre_z;
model.palette = palette;
model.ROC = [x_roc y_roc];
model.AUC = round(auc,2);
model.CV_accuracy_perm = CV_accuracy_perm;

%% Plot the model results (also saved to output data structure) %%%%%%%%%%%
[model.vipScores,model.vipNames,model.pAdjBH, model.indAccBH, model.univar_pvals] =...
    PLSDA_plot(model,categories,multilevel)

end